spec-version: 0.36.0
name: aoc2023
version: 0.8.0
synopsis: Advent of code, written in Haskell
author: Erik Grundy <erik.grundy@gmail.com>
maintainer: Erik Grundy <erik.grundy@gmail.com>
github: FourCredits/aoc2023
category: Development

dependencies:
  base:
    version: ">= 4.17.2 && < 4.18"
    mixin:
      - hiding (Prelude)
  relude:
    version: ^>= 1.2.1
    mixin:
      - (Relude as Prelude)
      - ""
  array: ">= 0.5.4 && < 0.6"
  parsec: ">= 3.1.16 && < 3.2"
  containers: "^>= 0.6.7"

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wpartial-fields
  - -Wredundant-constraints

default-extensions:
  - OverloadedStrings

data-files:
  - inputs/**/*

library:
  source-dirs: lib

executable:
  main: Main.hs
  source-dirs: app
  dependencies:
    - aoc2023
  generated-other-modules: Paths_aoc2023

tests:
  spec:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - hspec == 2.*
      - aoc2023
    build-tools: hspec-discover
    generated-other-modules: Paths_aoc2023
